version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: clinic-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 118896
      POSTGRES_DB: clinic
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
